/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_free_p7zip_Andro7za */

#ifndef _Included_com_free_p7zip_Andro7za
#define _Included_com_free_p7zip_Andro7za
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_free_p7zip_Andro7za
 * Method:    a7za_command
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_free_p7zip_Andro7za_a7zaCommand(JNIEnv *env, jobject obj, 
		jstring _command, 
		jstring _pathArchive,
		jstring _type,
		jstring _password,
		jstring _outputDirOrCompressionLevel,
		jstring _fList4CompressOrExtract);

#ifdef __cplusplus
}
#endif
#endif
